In [1]:
import pandas as pd
import numpy as np
from numpy import unique
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [35]:
#----------lets make the model for all patients-------------
# print('reading file number... 0')
data = pd.read_csv('../data/merged_patient0.csv')
for i in range(1,40):
#     print('reading file number...',i)
    data = pd.concat([data, pd.read_csv('../data/merged_patient'+str(i)+'.csv')],ignore_index=True)

y = data['expected_glucose']
x = data[data.columns[:-1]]

print('shape of the dataset...',x.shape)

#-----categorical data encoding ---------
cat = x[x.columns[-6:]]
print('number of categorical columns...',cat.shape[1])
encode = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame((encode.fit_transform(cat)).toarray())
enc_df.columns = ['RTG_h','RTG_l','RTG_n','RF_n','liver_i','liver_n','liver_r','peripheral_i','peripheral_n','peripheral_r','par1B', 'par1C', 'par1E', 'par1x','par2a', 'par2b', 'par2g', 'par2h', 'par2j', 'par2k', 'par2l', 'par2n', 'par2o', 'par2s', 'par2u', 'par2x']
# print(enc_df.shape)

x=x.drop(x.columns[-6:],axis=1)
x=x.drop(x.columns[0],axis=1)
x = x.join(enc_df)

print('created the x and y the dataset and expected glucose values...')
#-----x contains data without the time series-----
#-----y contains the values----------------

shape of the dataset... (3880, 32)
number of categorical columns... 6
created the x and y the dataset and expected glucose values...

In [36]:
#creating the training and testing datasets

x_train = x.loc[:len(x)*0.7]
x_test = x.loc[len(x)*0.7:]
y_train = y.loc[:len(x)*0.7]
y_test = y.loc[len(x)*0.7:]

print('shape of training dataset',x_train.shape)
print('testing dataset shape',x_test.shape)

shape of training dataset (2717, 51)
testing dataset shape (1164, 51)

In [37]:
x_train

,Weight(kg),t1,t2,t3,t4,t5,t6,c1,c2,c3,...,par2g,par2h,par2j,par2k,par2l,par2n,par2o,par2s,par2u,par2x
0,70,800,1000,1200,1550,1800,2230,30,20,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,70,800,1000,1200,1550,1800,2230,30,20,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,70,800,1000,1200,1550,1800,2230,30,20,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,70,800,1000,1200,1550,1800,2230,30,20,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,70,800,1000,1200,1550,1800,2230,30,20,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2712,75,800,1000,1300,1545,1800,2300,30,0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2713,75,800,1000,1300,1545,1800,2300,30,0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2714,75,800,1000,1300,1545,1800,2300,30,0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2715,75,800,1000,1300,1545,1800,2300,30,0,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2716,83,800,1000,1300,1545,1800,2200,20,0,15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.2.0-cp38-cp38-manylinux2010_x86_64.whl (516.3 MB)
     |██████████████████████████▏     | 422.2 MB 2.5 MB/s eta 0:00:38